[package]
name = "rustchain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cardano = "0.1.3"
cardano-multiplatform-lib = "3.1.3"
cardano-net = "0.2.1"
cardano-sdk = "0.2.5"
